FROM mysql:5.7


# ENV MYSQL_DATA_DIR=/var/lib/mysql \
#     MYSQL_RUN_DIR=/run/mysqld \
#     MYSQL_LOG_DIR=/var/log/mysql

# ADD ["nodelogin.sql", "/tmp/nodelogin.sql"]

# RUN /etc/init.d/mysql start && \
#          mysql -u root -p$MYSQL_ROOT_PASSWORD  -e "GRANT ALL PRIVILEGES ON *.* TO 'comeon'@'%' IDENTIFIED BY 'password';FLUSH PRIVILEGES;" && \
#         mysql -u root -p${MYSQL_ROOT_PASSWORD}  < /tmp/nodelogin.sql



# ADD var/www/html/adv_networking/init_db.sh var/www/html/adv_networking/tmp/init_db.sh
# RUN ./tmp/init_db.sh
